### ISSUE TITLE
PDC tracking issue

### ISSUE THREAD

**Issue by Robbert** [frameless/strapi#390]
- [x] API's en Website Alfabet-navigatie component maken
  - [Storybook: Index character navigation](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-index-char-nav--docs)
- [ ] Homepage maken
  - https://pdc.cg-intern.acc.utrecht.nl
  - @AliKdhim87: zijn de top task cards van homepage editable?
- [x] ~~Pandosearch index maken voor testomgeving~~
  - Het bleek onmogelijk te zijn voor Pandosearch om afgeschermde omgevingen zoals test en acceptatie te indexeren
- [x] Testdata voor de development-omgeving
- [ ] Afbeelding component Kolommen component
  - [ ] @AliKdhim87 Ik denk dat we deze component nog moeten refactoren om [Column layout](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css_css-column-layout--docs) component te gebruiken, en we hebben dan denk ik nog een extra onderdeel nodig: een container die als geheel altijd in één kolom blijft staan.
- [x] Sitemap.xml voor Pandosearch
  - Acceptatie-omgeving: https://pdc.cg-intern.acc.utrecht.nl/en/sitemap.xml
- [ ] Foutmelding pagina's maken
- [ ] PDC datamodel maken in Strapi
  - Dit moet nog verder afgerond worden volgens CimPDC 0.8, hier gaat @bddjong aan werken
- [ ] Zoekresultaten pagina maken
- [ ] Productpagina met alle eigen componenten
- [x] ~~Pandosearch index voor acceptatieomgeving~~
  - Het bleek onmogelijk te zijn voor Pandosearch om afgeschermde omgevingen zoals test en acceptatie te indexeren
- [ ] Datamodel voor samenwerkende catalogi
- [ ] npm package met OWMS data in JSON
- [x] npm package met Uniforme Productnamenlijst in JSON
  - https://github.com/frameless/strapi/tree/main/packages/upl
- [x] Image uploads in Strapi
- [x] Microservice voor Samenwerkende Catalogi
  - @AliKdhim87 Heb je een linkje?
- [ ] Cookie consent bar component
- [ ] Zoeken met autocomplete
  - [x] Werkt in de website, maar component moet nog gemigreerd worden naar het design system
  - [ ] @Robbert component PR nog mergen 🙈 https://github.com/nl-design-system/utrecht/pull/1867
  - [ ] @Robbert andere PR nog mergen: https://github.com/nl-design-system/utrecht/pull/1374
- [x] Spike: rich text editor voor Strapi blokken
  - We zijn [Tip-Tap](http://tiptap.dev) gaan gebruiken in plaats van [CKEditor](https://ckeditor.com)
- [ ] Pandosearch index voor productieomgeving
  - [x] sitemap.xml is beschikbaar voor Pandosearch: https://pdc.cg-intern.utrecht.nl/sitemap.xml
  - [ ] productie-omgeving kan pas geïndexeerd worden wanneer de omgeving publiek is bij lancering
- [ ] Accordion animatie
  - [x] Accordion animatie maken
  - [ ] @Robbert: nog de PR reviewen in het design system
  - [ ] Nieuwe accordion-versie in gebruik nemen
- [ ] "Naar boven" link component
  - [x] "Naar boven" component maken
  - [x] "Naar boven" component in gebruik nemen
  - [ ] @Robbert: nog de PR reviewen in het design system
  - [ ] Switchen naar component uit design system
- [ ] Feedback verwerken na testen voor toegankelijkheid door externe partij
  - Er is nog geen toegankelijkheids-check gedaan, dit is voor nazorg
- [ ] PDC API microservice maken
  - Hier moet @bddjong aan gaan werken
- [ ] Datamodel voor toptaken/navigatie/footer op de homepage

Extra dingetjes die we nog moeten doen:

- [ ] Dark mode uitschakelen tot die afgerond en getest is

**Comment by AliKdhim87** [comment]
- [x] Foutmelding pagina's maken: Als er frontend-validatiefouten zijn, heb ik deze geïmplementeerd. Bijvoorbeeld 404, 500, server issues.

**Comment by AliKdhim87** [comment]
- [ ] Cookie consent bar component? We hebben het stijl nodig en moeten weten waar het wordt gebruikt, want tot nu toe gebruiken we geen cookies, behalve voor de testmodus waarvoor ik al een component heb gemaakt.
<img width="1437" alt="Screenshot 2024-01-24 at 09 23 48" src="https://github.com/frameless/strapi/assets/53454241/42738698-627d-493a-9cc5-0e6946bf9b56">

**Comment by AliKdhim87** [comment]
- [ ] Homepage maken 
  -  zijn de top task cards van homepage editable? nog niet. Daar heb ik nog paar vragen 

- Is het zo dat de top taken producten alleen deze zes producten omvat?
- Als dat zo is, moet ik een extra property toevoegen aan elk product, bijvoorbeeld een checkbox genaamd topTasks [x].
- Wat is het verschil tussen de topTasks van utrecht.nl en https://pki.utrecht.nl/Loket/start.do?
 - Als je naar de foto hieronder kijkt, zie je dat sommige top taken gemengde pagina's hebben van utrecht.nl en pki pages.

 **pki.utrecht.nl**:
<img width="732" alt="Screenshot 2024-01-24 at 09 41 21" src="https://github.com/frameless/strapi/assets/53454241/1b8b56b5-5f0a-46b4-bb0e-2fefbf79d910">


**https://www.utrecht.nl/**:

<img width="677" alt="Screenshot 2024-01-24 at 09 56 02" src="https://github.com/frameless/strapi/assets/53454241/ca07d163-b898-4a1b-bf81-bcabaf03f129">

**Comment by bddjong** [comment]
#399 PR in progress voor CimPDC ondersteuning
