### ISSUE TITLE
Open Forms API snelheid

### ISSUE THREAD

**Issue by bddjong** [frameless/strapi#579]
De `/forms` api is erg traag en zorgt bij voor formulieren voor een lange laadtijd voor redacteuren. We gebruiken die API in de `strapi-plugin-open-forms` om een lijst van formulieren op te halen die gekoppeld kunnen worden aan een Call to Action button in strapi.

Sinds Open Forms 2.6.0 is er een nieuwe API (`/public/forms`) die sneller zou moeten werken ([Swagger docs](/api/v2/public/forms/))

![Image](https://github.com/frameless/strapi/assets/24610692/bb41cdee-f93e-4ef4-95b3-53086d3b42ab)

### Tasks
- [x] **Controleer of Utrecht updated is naar Open Forms 2.6.0**
- [x] Pas de `strapi-plugin-open-forms` package aan om een request te doen naar de nieuwe API ipv de oude API
- [ ] Test resultaten met de CTA form dropdown in de strapi interface

**Comment by bddjong** [comment]
Opnieuw checken wat het plan is voor een snellere API voor form listing

**Comment by bddjong** [comment]
Nieuwe snelle endpoints zitten nu in Open Formulieren (2.6.0?), afhankelijk van Utrecht om te upgraden naar deze versie.
